source 'https://rubygems.org'

gem 'cinch', '~>2.2.6'
gem 'cinch-spotify'
gem 'cinch-downforeveryone'
gem 'cinch-last_seen'
gem 'marky_markov', '~>0.3.5'
gem 'mechanize'
gem 'bitly'
gem 'nokogiri'
gem 'iconv'
gem 'json'
gem 'sqlite3'
gem 'wolfram'
gem 'dicks-api'
gem 'htmlentities'